version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:3.6.0
    environment:
      RENV_PATHS_CACHE: /home/renv/cache
      RENV_PATHS_LIBRARY: /home/renv/library
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'renv-lock-{{ checksum "renv.lock" }}'
            - 'renv-lock'

      - run:
          name: Install dependencies
          command: Rscript -e "renv::hydrate(); renv::restore(); renv::clean()"

      - run:
          name: Build package
          command: Rscript -e "rmarkdown::render(input = 'test.Rmd', output_dir = 'output_dir')"

      - store_artifacts: { path: ~/project/output_dir }

      - save_cache:
          key: 'renv-lock-{{ checksum "renv.lock" }}'
          paths:
            - /home/renv

      - run:
          name: Check dependencies are correctly recorded in renv.lock
          command: |
            Rscript -e "renv::snapshot()"
            if ! git diff --exit-code ; then
                echo "Seems like renv.lock needs updating, please run 'renv::snapshot()' in Rstudio or 'Rscript -e \"renv::snapshot()\"' in your Terminal"
            fi

workflows:
  version: 2
  all:
    jobs:
      - build
