version: 2
jobs:
  build:
    docker:
      - image: rocker/verse:3.6.0
    environment:
      RENV_PATHS_CACHE: /home/renv/cache
      RENV_PATHS_LIBRARY: /home/renv/library
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'renv-{{ .Environment.CIRCLE_JOB }}-{{ checksum "renv.lock" }}'
            - 'renv-{{ .Environment.CIRCLE_JOB }}'
      - run:
          name: Install dependencies
          command: Rscript -e "renv::hydrate(); renv::restore(); renv::clean()"
      - run:
          name: Build package
          command: Rscript -e "rmarkdown::render(input = 'test.Rmd', output_dir = 'output_dir')"
      - store_artifacts: { path: ~/project/output_dir }
      - save_cache:
          key: 'renv-{{ .Environment.CIRCLE_JOB }}-{{ checksum "renv.lock" }}'
          paths: [ /home/renv ]
      - run:
          name: Check dependencies are correctly recorded in renv.lock
          command: |
            Rscript -e "renv::snapshot()"
            if ! git diff --exit-code ; then
                echo "Seems like renv.lock needs updating, please run 'renv::snapshot()' in Rstudio or 'Rscript -e \"renv::snapshot()\"' in your Terminal"
            fi

  styler:
    docker:
      - image: rocker/r-ver:3.6.0
    environment:
      RENV_PATHS_CACHE: /home/renv/cache
      RENV_PATHS_LIBRARY: /home/renv/library
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'renv-{{ .Environment.CIRCLE_JOB }}-{{ checksum "renv.lock" }}'
            - 'renv-{{ .Environment.CIRCLE_JOB }}'
      - run:
          name: Install dependencies
          command: Rscript -e 'install.packages("styler")'
      - run: Rscript -e 'styler::style_dir()'
      - save_cache:
          key: 'renv-{{ .Environment.CIRCLE_JOB }}-{{ .BuildNum }}'
          paths: [ /home/renv ]
          when: always
      - run:
          name: Check repo is up to date
          command: |
            apt-get update
            apt-get install -y git
            if ! git diff --exit-code ; then
                echo "Seems like style needs needs updating, please run 'styler::style_dir()' in Rstudio or 'Rscript -e \"styler::style_dir()\"' in your Terminal"
                exit 1
            fi
      - store_artifacts:
          path: ~/project
          when: always

  lintr:
    docker:
      - image: rocker/r-ver:3.6.0
    environment:
      RENV_PATHS_CACHE: /home/renv/cache
      RENV_PATHS_LIBRARY: /home/renv/library
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'renv-{{ .Environment.CIRCLE_JOB }}-{{ .BuildNum }}'
            - 'renv-{{ .Environment.CIRCLE_JOB }}'
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y curl
            Rscript -e 'install.packages("lintr")'
      - run: Rscript -e 'lintr::lint_dir()'
      - save_cache:
          key: 'renv-{{ .Environment.CIRCLE_JOB }}-{{ .BuildNum }}'
          paths: [ /home/renv ]
          when: always

workflows:
  version: 2
  all:
    jobs:
      - build
      - styler
      - lintr
